### ISSUE TITLE
Could FEAST directly apply to Single-cell dataset that is TPM or FPKM format?

### ISSUE THREAD

**Issue by kewos-0610** [suke18/FEAST#1]
Dear author of FEAST,
I am a master's student, now working on biological network related-researches. I want to ask could FEAST directly apply to Single-cell dataset that is TPM or FPKM format. I have some datasets that have been normalized, but I don’t know how to reverse the format to raw counts format.

It will be very helpful to my master’s research if you answer my question. Thank you.

Best Regards,
Wei-Jie Wang

**Comment by suke18** [comment]
I am sorry for the late response. Yes. You can apply the FEAST function. If is a pre-normalized expression matrix, you can directly use it as an input.
