### ISSUE TITLE
Orders to respect to perform feature selction combinig Seurat and FEAST

### ISSUE THREAD

**Issue by SHADJIA** [suke18/FEAST#2]
Hello Kenong Su,

I read your article about feature selection for scRNA seq datasets using your FEAST package. I'm a master's student and I have a project to determine the minimal number of genes needed to delineate subsets of Treg cells. I use Seurat for the data analysis. I would like to test your tool to find wether I get a "small" number of genes rather than 2000 HVGs determined in Seurat for my downstream analysis.

I would like to have your advice in the order of the steps to respect. I think about taking the raw data and perform "process_Y" to normalize the data and continue the process as you decribe in Yan vignette. Once the list of optimal genes determined, I will feed them into "VariableFeatures" of Seurat and continue the analysis. 

Should I use the raw data or should I perform the QC analysis of Seurat to filter out doublets and mitochondrial genes and then use the filtered data as input in FEAST?

Thank you in advance for your guidance.

Best regards,
Sha

**Comment by suke18** [comment]
Hello Sha, 

Thanks for your interest in using FEAST. Yes, once you obtained the list of genes generated by FEAST, you can feed into some existing clustering algorithms such as Seurat.  As for the process of the Seurat object, I think you can just follow the Seurat user guide. I think you need to do QC step. https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

Best,
Kenong

**Comment by SHADJIA** [comment]
Hello Kenong,

Thanks for your reply.
